
MODEL_FIELD_QUERY = "query"
MODEL_FIELD_FORMATTED = "formatted"
MODEL_FIELD_PROVIDER_CODE_EQUALITY = "provider_code_equality"
MODEL_FIELD_LIMIT = "limit"
MODEL_FIELD_SKIP = "skip"

SCOPE_DIRECTORY_API = 'directory_api'

SCOPE_ALL = 'all'

AVAILABLE_SCOPES = [SCOPE_DIRECTORY_API, SCOPE_ALL]
